{% set version = "1.15" %}

package:
  name: libiconv
  version: {{ version }}

source:
  url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-{{ version }}.tar.gz
  sha256: ccf536620a45458d26ba83887a983b96827001e92a13847b45e4925cc8913178
  patches:
    - glibc.patch  # [linux]
    - CMakeLists.txt.patch  # [win]
    - config.h.patch  # [win]
    - configure.cmake.patch  # [win]

build:
  number: 5
  skip: true  # [win and py35]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - cmake   # [win]
    - {{ compiler('c') }}

test:
  commands:
    - iconv --help  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.gnu.org/software/libiconv/
  license: GPL and LGPL
  summary: "Provides iconv for systems which don't have one (or that cannot convert from/to Unicode.)"
  
  description: |
    This library provides an iconv() implementation, for use on systems which don't have one, 
    or whose implementation cannot convert from/to Unicode.
  doc_url: https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.15/iconv.1.html
  dev_url: http://git.savannah.gnu.org/cgit/libiconv.git/tree/
  doc_source_url: 


extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - jhamman
