
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "zh+xHntq7bly+50YH89aLtmMtIbLkupbRsl3t1vTdOOBxvgFF09PKAGNUQJv4snrmBEOawftMMxPZ0UuTZnmfv+EPHK4kyuTpXMD1NMogGRBXis8iO57nN1zhBiEtGKj9ctCS833uxZmqkD95kNs2TDIyEfnln+xhgyXzwbqhFCOgonUGhCWjpUpgFexxcnvaXj+kHRFcBco6FEQ0bW4CJfCHZstRl20pcHKwmga9GvS8+INFlqui6NgGtaGzSuY9xo0t4j6XHJKC/ABJFSJ5l7tVjOj18dJbi4GG7we6lsiEOybnd3mx2jau8NSmQ2kFx7ALBkHzDHV/mkViex4yoTCQfF/FWMGRNy4HHBtibYNGbghOMIHER3DvQRY+KBQ7JYD6ypZpuUBBGnVF/Xvzu9O6M+bfkaynOfa06E5N2aJ9UJdHg2t+1Dn+bYj4KMgj39Y9BRqb6LngDts2kYdSh86jSFgxDUXj9udSAOhGDq29gd3PhPIJbJpzsLTLpLil6Q28hYSfCO/wuTZbRcICgzHrG2lYGZpWP25tDxW1Siw08juCR2I03IEa6v5IGzxbB4f4GIV9an4qaXEgYVhJ49Uo66u9I7aVeG3dmbHphPMbAL/ebZo1xRu8T25h/aHXiIKO3pTTOBYLjW01O8PQ9Kh/Gw9ZFDcDUyfi3s+N80="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
