travis:
  secure:
    BINSTAR_TOKEN: zh+xHntq7bly+50YH89aLtmMtIbLkupbRsl3t1vTdOOBxvgFF09PKAGNUQJv4snrmBEOawftMMxPZ0UuTZnmfv+EPHK4kyuTpXMD1NMogGRBXis8iO57nN1zhBiEtGKj9ctCS833uxZmqkD95kNs2TDIyEfnln+xhgyXzwbqhFCOgonUGhCWjpUpgFexxcnvaXj+kHRFcBco6FEQ0bW4CJfCHZstRl20pcHKwmga9GvS8+INFlqui6NgGtaGzSuY9xo0t4j6XHJKC/ABJFSJ5l7tVjOj18dJbi4GG7we6lsiEOybnd3mx2jau8NSmQ2kFx7ALBkHzDHV/mkViex4yoTCQfF/FWMGRNy4HHBtibYNGbghOMIHER3DvQRY+KBQ7JYD6ypZpuUBBGnVF/Xvzu9O6M+bfkaynOfa06E5N2aJ9UJdHg2t+1Dn+bYj4KMgj39Y9BRqb6LngDts2kYdSh86jSFgxDUXj9udSAOhGDq29gd3PhPIJbJpzsLTLpLil6Q28hYSfCO/wuTZbRcICgzHrG2lYGZpWP25tDxW1Siw08juCR2I03IEa6v5IGzxbB4f4GIV9an4qaXEgYVhJ49Uo66u9I7aVeG3dmbHphPMbAL/ebZo1xRu8T25h/aHXiIKO3pTTOBYLjW01O8PQ9Kh/Gw9ZFDcDUyfi3s+N80=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
